version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: events-space-postgres
    restart: unless-stopped
    # environment:
      # POSTGRES_DB: ${POSTGRES_DB}
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     
    environment:
      POSTGRES_DB: events_space
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
